### PR TITLE
Vra cache creds

### PR DESCRIPTION
**Pull request by michaelschlies**
Added support for VRA Credentials to be cached in an OpenSSL Encrypted cache file.

### CODE REVIEW

**Comment by ryangribble** [comment]
Is this change likely to be reviewed/merged?  

From looking at the code (and with my limited ruby knowledge) am I correct in thinking that with this change, the user is prompted for VRA user/pwd when they first attempt to use this driver, and is encrypted/stored locally and not added to source control?

As we are using AD user accounts for access to VRA it's a no go for us to be storing these in the kitchen.yml file in clear text, so this change sounds great

**Comment by michaelschlies** [comment]
That's the scenario one of my clients is in as well. While you can use environment variables they aren't always the easiest thing to so this felt like a usable option that most anyone could follow.

**Comment by jjasghar** [comment]
I'm in the process of building my VRA instance. As soon as I can verify this I'll be able to merge it.

**Comment by ryangribble** [comment]
> I'm in the process of building my VRA instance. As soon as I can verify this I'll be able to merge it.

Just wondering how this went?

**Comment by michaelschlies** [comment]
@jjasghar Is there any update on your test of this PR?

**Comment by jjasghar** [comment]
I have not been able to set up a successful vRA instance. If yall really want this I can push it out, but until I get an environment where I can consistently test things like this I'm not sure what to do.

**Comment by michaelschlies** [comment]
I can't speak for @ryangribble, I have only tested this on a brand new vRA 7.1 implementation.

**Comment by ryangribble** [comment]
We want to use kitchen against vra 7 but weren't keen on domain credentials in th kitchen file so haven't done anything yet. If you're able to indicate how we could run this branch ourselves locally I could test it

**Comment by jjasghar** [comment]
Can you rebase this off master please?

**Comment by jjasghar** [comment]
I'm ready to release this as soon as it's rebased 🤘

**Comment by michaelschlies** [comment]
Rebased and squashed

**Comment by jjasghar** [comment]
Awesome! thanks for this. :)

**Pull request merged**
